todos = Todo.create([
  {description: "Almond Milk", done: true},
  {description: "Almonds", done: true},
  {description: "Bread", done: true},
  {description: "Cashews", done: true},
  {description: "Cat Food", done: true},
  {description: "Cat Litter", done: true},
  {description: "Cherries", done: true},
  {description: "Craisins", done: true},
  {description: "Dishwasher Pellets", done: true},
  {description: "Emergen-C", done: true},
  {description: "Garbage Bags(33 gal)", done: true},
  {description: "Hemp Seeds", done: true},
  {description: "Kettle Chips", done: true},
  {description: "Laundry Soap", done: true},
  {description: "Mixed Nuts", done: true},
  {description: "Paper Towels", done: true},
  {description: "Peanut Butter", done: true},
  {description: "Pistacios", done: true},
  {description: "Pita Chips", done: true},
  {description: "Q'ia", done: true},
  {description: "Quinoa", done: true},
  {description: "Salsa", done: true},
  {description: "Sparkling Water", done: true},
  {description: "Strawberry Jam", done: true},
  {description: "Sun Dried Tomatoes", done: true},
  {description: "Toilet Paper", done: true},
  {description: "Walnuts", done: true}
])
